"""应用层端口：适配器可替换，业务服务通过构造函数获取依赖。"""

from abc import ABC, abstractmethod
from collections.abc import Iterator
from contextlib import AbstractContextManager
from pathlib import Path
from typing import Any, Protocol

from back.domain.chat import CacheHit, ChatState, SessionKey, SessionSnapshot
from back.domain.tenant import KnowledgeSource, TenantProfile


class SessionRepository(ABC):
    @abstractmethod
    def load(self, key: SessionKey) -> SessionSnapshot: ...

    @abstractmethod
    def save(self, key: SessionKey, state: ChatState, expected_version: int) -> None:
        """原子地检查版本并保存；冲突必须抛出 Conflict。"""


class ChatEngine(Protocol):
    def invoke(self, state: ChatState) -> ChatState: ...
    def stream(self, state: ChatState) -> Iterator[dict[str, Any]]: ...


class AnswerCache(Protocol):
    def find(self, tenant_id: str, question: str) -> CacheHit | None: ...
    def revision(self, tenant_id: str) -> int | None: ...
    def store(self, tenant_id: str, question: str, answer: str, *, expected_revision: int | None = None) -> bool: ...
    def invalidate(self, tenant_id: str) -> int: ...
    def mutation(self, tenant_id: str) -> AbstractContextManager[None]: ...


class TenantReader(Protocol):
    def get(self, tenant_id: str) -> TenantProfile | None: ...


class TenantRepository(TenantReader, Protocol):
    def create(self, profile: TenantProfile) -> None:
        """原子创建租户；已存在时抛出 Conflict，不覆盖资料。"""
    def save(self, profile: TenantProfile) -> None: ...


class KnowledgeRepository(Protocol):
    def operation(self, tenant_id: str, source_id: str) -> AbstractContextManager[None]: ...
    def get(self, source_id: str) -> KnowledgeSource | None: ...
    def list(self, tenant_id: str) -> list[KnowledgeSource]: ...
    def save(self, source: KnowledgeSource) -> None: ...
    def delete(self, source_id: str) -> bool: ...


class SourceFiles(Protocol):
    def write(self, tenant_id: str, source_id: str, name: str, content: bytes) -> Path: ...
    def path(self, source: KnowledgeSource) -> Path: ...
    def delete(self, source: KnowledgeSource) -> None: ...


class KnowledgeIndexer(Protocol):
    def index(self, source: KnowledgeSource, path: Path) -> KnowledgeSource: ...
    def delete(self, tenant_id: str, source_id: str) -> int: ...


class ImageInterpreter(Protocol):
    def describe(self, content: bytes, message: str, tenant_id: str) -> str: ...
